updated_at: "2026-06-14"

tiers:
  A:
    - paypal
    - cisco
    - nordea
    - ericsson
    - volvo cars
    - saab
    - ubs
    - arm
    - noda
    - klarna
    - spotify
    - seb
    - scania
    - axis
    - zenseact
    - astrazeneca
    - google sweden
    - microsoft sweden
    - amazon
    - nvidia
    - apple
    - paradox interactive
    - mojang
    - truecaller
    - mentimeter
    - einride
    - sana labs
    - lovable
    - ikea
    - h&m
    - polestar
    - abb
    - nordea
    - handelsbanken
    - telia
  B:
    - aws sweden
    - detectify
    - yubico
    - instabee
    - anyfin
    - juni
    - normative
    - mathem
    - doktor.se
    - synopsys
  C: []
