ALTER TABLE public.user_profile
  ADD COLUMN IF NOT EXISTS first_name TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS last_name TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS email TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS phone TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS about_me TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS autofill_extra JSONB NOT NULL DEFAULT '{}'::jsonb;
